// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/approve-distributor': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/approve-distributor.post').default>>>>
    }
    '/api/orders/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/create.post').default>>>>
    }
    '/api/pdf/generate-po': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pdf/generate-po.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}