// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/10/2026, 9:14:45 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/daniel/Documents/GitHub/manpaB2B/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/daniel/Documents/GitHub/manpaB2B/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/daniel/Documents/GitHub/manpaB2B/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/daniel/Documents/GitHub/manpaB2B/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/daniel/Documents/GitHub/manpaB2B/app/plugins/**/*.{js,ts,mjs}","/home/daniel/Documents/GitHub/manpaB2B/app/composables/**/*.{js,ts,mjs}","/home/daniel/Documents/GitHub/manpaB2B/app/utils/**/*.{js,ts,mjs}","/home/daniel/Documents/GitHub/manpaB2B/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/daniel/Documents/GitHub/manpaB2B/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/daniel/Documents/GitHub/manpaB2B/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/daniel/Documents/GitHub/manpaB2B/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;